# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#intent:
rest_command:
    rhasspy_speak:
        url: 'http://192.168.178.17:12101/api/text-to-speech'
        method: 'POST'
        payload: '{{ payload }}'
        content_type: 'text/plain'
group: !include groups.yaml
automation: !include_dir_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml